const spanishWords = [
  // Beginner (1-15)
  {
    id: "word001",
    word: "hola",
    pronunciation: "oh-lah",
    meaning: "hello",
    part_of_speech: "expression",
    difficulty: "easy",
    lesson_no: 1,
    when_to_say: "Used to greet someone casually.",
    example: "Hola, ¿cómo estás? - Hello, how are you?",
  },
  {
    id: "word002",
    word: "adiós",
    pronunciation: "ah-dee-ohs",
    meaning: "goodbye",
    part_of_speech: "expression",
    difficulty: "easy",
    lesson_no: 1,
    when_to_say: "Used when parting ways.",
    example: "Adiós, nos vemos mañana. - Goodbye, see you tomorrow.",
  },
  {
    id: "word003",
    word: "gracias",
    pronunciation: "grah-syahs",
    meaning: "thank you",
    part_of_speech: "expression",
    difficulty: "easy",
    lesson_no: 1,
    when_to_say: "Used to express gratitude.",
    example: "Gracias por tu ayuda. - Thank you for your help.",
  },
  {
    id: "word004",
    word: "por favor",
    pronunciation: "por fah-vohr",
    meaning: "please",
    part_of_speech: "expression",
    difficulty: "easy",
    lesson_no: 1,
    when_to_say: "Used to make polite requests.",
    example: "Pásame la sal, por favor. - Pass me the salt, please.",
  },
  {
    id: "word005",
    word: "sí",
    pronunciation: "see",
    meaning: "yes",
    part_of_speech: "adverb",
    difficulty: "easy",
    lesson_no: 1,
    when_to_say: "Used to affirm or agree.",
    example: "Sí, quiero un café. - Yes, I want a coffee.",
  },
  {
    id: "word006",
    word: "no",
    pronunciation: "noh",
    meaning: "no",
    part_of_speech: "adverb",
    difficulty: "easy",
    lesson_no: 1,
    when_to_say: "Used to negate or disagree.",
    example: "No, no tengo tiempo. - No, I don't have time.",
  },
  {
    id: "word007",
    word: "amigo",
    pronunciation: "ah-mee-goh",
    meaning: "friend",
    part_of_speech: "noun",
    difficulty: "easy",
    lesson_no: 2,
    when_to_say: "Used to refer to a male friend.",
    example: "Juan es mi mejor amigo. - Juan is my best friend.",
  },
  {
    id: "word008",
    word: "amiga",
    pronunciation: "ah-mee-gah",
    meaning: "friend",
    part_of_speech: "noun",
    difficulty: "easy",
    lesson_no: 2,
    when_to_say: "Used to refer to a female friend.",
    example: "Ana es mi mejor amiga. - Ana is my best friend.",
  },
  {
    id: "word009",
    word: "familia",
    pronunciation: "fah-mee-lee-ah",
    meaning: "family",
    part_of_speech: "noun",
    difficulty: "easy",
    lesson_no: 2,
    when_to_say: "Used to refer to relatives collectively.",
    example: "Mi familia es muy unida. - My family is very close.",
  },
  {
    id: "word010",
    word: "comida",
    pronunciation: "koh-mee-dah",
    meaning: "food",
    part_of_speech: "noun",
    difficulty: "easy",
    lesson_no: 2,
    when_to_say: "Used when referring to meals or dishes.",
    example: "La comida mexicana es deliciosa. - Mexican food is delicious.",
  },
  {
    id: "word011",
    word: "agua",
    pronunciation: "ah-gwah",
    meaning: "water",
    part_of_speech: "noun",
    difficulty: "easy",
    lesson_no: 2,
    when_to_say: "Used to refer to drinking or any kind of water.",
    example:
      "¿Puedes darme un vaso de agua? - Can you give me a glass of water?",
  },
  {
    id: "word012",
    word: "casa",
    pronunciation: "kah-sah",
    meaning: "house",
    part_of_speech: "noun",
    difficulty: "easy",
    lesson_no: 3,
    when_to_say: "Used to refer to someone's home.",
    example: "Mi casa es tu casa. - My house is your house.",
  },
  {
    id: "word013",
    word: "perro",
    pronunciation: "peh-rroh",
    meaning: "dog",
    part_of_speech: "noun",
    difficulty: "easy",
    lesson_no: 3,
    when_to_say: "Used to refer to a canine.",
    example: "Mi perro se llama Max. - My dog's name is Max.",
  },
  {
    id: "word014",
    word: "gato",
    pronunciation: "gah-toh",
    meaning: "cat",
    part_of_speech: "noun",
    difficulty: "easy",
    lesson_no: 3,
    when_to_say: "Used to refer to a feline.",
    example: "Tengo un gato negro. - I have a black cat.",
  },
  {
    id: "word015",
    word: "escuela",
    pronunciation: "es-kweh-lah",
    meaning: "school",
    part_of_speech: "noun",
    difficulty: "easy",
    lesson_no: 3,
    when_to_say: "Used to refer to a place for learning.",
    example: "Voy a la escuela todos los días. - I go to school every day.",
  },

  {
    id: "word016",
    word: "trabajar",
    pronunciation: "trah-bah-har",
    meaning: "to work",
    part_of_speech: "verb",
    difficulty: "medium",
    lesson_no: 4,
    when_to_say: "Used to describe performing a job or task.",
    example: "Tengo que trabajar mañana. - I have to work tomorrow.",
  },
  {
    id: "word017",
    word: "estudiar",
    pronunciation: "es-too-dee-ar",
    meaning: "to study",
    part_of_speech: "verb",
    difficulty: "medium",
    lesson_no: 4,
    when_to_say: "Used to describe the act of learning.",
    example:
      "Voy a estudiar para el examen. - I am going to study for the exam.",
  },
  {
    id: "word018",
    word: "leer",
    pronunciation: "leh-ehr",
    meaning: "to read",
    part_of_speech: "verb",
    difficulty: "medium",
    lesson_no: 4,
    when_to_say:
      "Used when talking about reading books, articles, or documents.",
    example: "Me gusta leer novelas. - I like to read novels.",
  },
  {
    id: "word019",
    word: "escuchar",
    pronunciation: "es-koo-char",
    meaning: "to listen",
    part_of_speech: "verb",
    difficulty: "medium",
    lesson_no: 5,
    when_to_say: "Used to describe the act of hearing attentively.",
    example: "Escucho música todos los días. - I listen to music every day.",
  },
  {
    id: "word020",
    word: "viajar",
    pronunciation: "vee-ah-har",
    meaning: "to travel",
    part_of_speech: "verb",
    difficulty: "medium",
    lesson_no: 5,
    when_to_say: "Used to describe moving to different places.",
    example: "Quiero viajar a España. - I want to travel to Spain.",
  },
  {
    id: "word021",
    word: "correr",
    pronunciation: "koh-rehr",
    meaning: "to run",
    part_of_speech: "verb",
    difficulty: "medium",
    lesson_no: 5,
    when_to_say: "Used to describe jogging or running.",
    example: "Corro todas las mañanas. - I run every morning.",
  },
  {
    id: "word022",
    word: "hermoso",
    pronunciation: "ehr-moh-soh",
    meaning: "beautiful",
    part_of_speech: "adjective",
    difficulty: "medium",
    lesson_no: 6,
    when_to_say: "Used to describe something aesthetically pleasing.",
    example: "El paisaje es hermoso. - The scenery is beautiful.",
  },
  {
    id: "word023",
    word: "rápido",
    pronunciation: "rah-pee-doh",
    meaning: "fast",
    part_of_speech: "adjective",
    difficulty: "medium",
    lesson_no: 6,
    when_to_say: "Used to describe something quick in speed.",
    example: "Este coche es muy rápido. - This car is very fast.",
  },
  {
    id: "word024",
    word: "importante",
    pronunciation: "eem-por-tahn-teh",
    meaning: "important",
    part_of_speech: "adjective",
    difficulty: "medium",
    lesson_no: 6,
    when_to_say: "Used to highlight significance.",
    example: "Es importante estudiar. - It is important to study.",
  },
  {
    id: "word025",
    word: "dormir",
    pronunciation: "dor-meer",
    meaning: "to sleep",
    part_of_speech: "verb",
    difficulty: "medium",
    lesson_no: 7,
    when_to_say: "Used to describe resting at night.",
    example: "Necesito dormir ocho horas. - I need to sleep eight hours.",
  },
  {
    id: "word026",
    word: "ventana",
    pronunciation: "ven-tah-nah",
    meaning: "window",
    part_of_speech: "noun",
    difficulty: "medium",
    lesson_no: 7,
    when_to_say: "Used to describe an opening in a wall.",
    example: "La ventana está abierta. - The window is open.",
  },
  {
    id: "word027",
    word: "puerta",
    pronunciation: "pwehr-tah",
    meaning: "door",
    part_of_speech: "noun",
    difficulty: "medium",
    lesson_no: 7,
    when_to_say: "Used to describe the entry to a building or room.",
    example: "Cierra la puerta, por favor. - Close the door, please.",
  },
  {
    id: "word028",
    word: "jugar",
    pronunciation: "hoo-gar",
    meaning: "to play",
    part_of_speech: "verb",
    difficulty: "medium",
    lesson_no: 8,
    when_to_say: "Used to talk about playing games or sports.",
    example: "A los niños les gusta jugar. - Kids like to play.",
  },
  {
    id: "word029",
    word: "esperar",
    pronunciation: "es-peh-rahr",
    meaning: "to wait",
    part_of_speech: "verb",
    difficulty: "medium",
    lesson_no: 8,
    when_to_say: "Used to describe being patient or waiting.",
    example:
      "Espero el autobús todos los días. - I wait for the bus every day.",
  },
  {
    id: "word030",
    word: "mujer",
    pronunciation: "moo-hehr",
    meaning: "woman",
    part_of_speech: "noun",
    difficulty: "medium",
    lesson_no: 8,
    when_to_say: "Used to refer to an adult female.",
    example: "Esa mujer es muy amable. - That woman is very kind.",
  },
  {
    id: "word031",
    word: "hombre",
    pronunciation: "ohm-breh",
    meaning: "man",
    part_of_speech: "noun",
    difficulty: "medium",
    lesson_no: 9,
    when_to_say: "Used to refer to an adult male.",
    example: "Ese hombre es muy trabajador. - That man is very hardworking.",
  },
  {
    id: "word032",
    word: "inteligente",
    pronunciation: "een-teh-lee-hen-teh",
    meaning: "intelligent",
    part_of_speech: "adjective",
    difficulty: "medium",
    lesson_no: 9,
    when_to_say: "Used to describe someone smart or clever.",
    example: "Mi hermana es muy inteligente. - My sister is very intelligent.",
  },
  {
    id: "word033",
    word: "pequeño",
    pronunciation: "peh-keh-nyoh",
    meaning: "small",
    part_of_speech: "adjective",
    difficulty: "medium",
    lesson_no: 9,
    when_to_say: "Used to describe size.",
    example: "El perro es pequeño. - The dog is small.",
  },
  {
    id: "word034",
    word: "grande",
    pronunciation: "grahn-deh",
    meaning: "big",
    part_of_speech: "adjective",
    difficulty: "medium",
    lesson_no: 9,
    when_to_say: "Used to describe size.",
    example: "La casa es grande. - The house is big.",
  },
  {
    id: "word035",
    word: "feliz",
    pronunciation: "feh-lees",
    meaning: "happy",
    part_of_speech: "adjective",
    difficulty: "medium",
    lesson_no: 9,
    when_to_say: "Used to describe someone's mood or state.",
    example: "Estoy muy feliz hoy. - I am very happy today.",
  },
  {
    id: "word036",
    word: "desafío",
    pronunciation: "deh-sah-fee-oh",
    meaning: "challenge",
    part_of_speech: "noun",
    difficulty: "difficult",
    lesson_no: 10,
    when_to_say: "Used to describe a difficult task or situation.",
    example:
      "El proyecto es un gran desafío. - The project is a big challenge.",
  },
  {
    id: "word037",
    word: "responsabilidad",
    pronunciation: "rehs-pon-sah-bee-lee-dahd",
    meaning: "responsibility",
    part_of_speech: "noun",
    difficulty: "difficult",
    lesson_no: 10,
    when_to_say: "Used to talk about obligations or duties.",
    example:
      "Es mi responsabilidad cuidar a mis hijos. - It is my responsibility to take care of my children.",
  },
  {
    id: "word038",
    word: "aprovechar",
    pronunciation: "ah-pro-veh-char",
    meaning: "to take advantage of",
    part_of_speech: "verb",
    difficulty: "difficult",
    lesson_no: 10,
    when_to_say: "Used to express making use of an opportunity.",
    example:
      "Debemos aprovechar el tiempo. - We should take advantage of the time.",
  },
  {
    id: "word039",
    word: "desarrollar",
    pronunciation: "deh-sah-roh-yar",
    meaning: "to develop",
    part_of_speech: "verb",
    difficulty: "difficult",
    lesson_no: 10,
    when_to_say: "Used to talk about growth or improvement.",
    example:
      "Queremos desarrollar nuevas habilidades. - We want to develop new skills.",
  },
  {
    id: "word040",
    word: "complicado",
    pronunciation: "kohm-plee-kah-doh",
    meaning: "complicated",
    part_of_speech: "adjective",
    difficulty: "difficult",
    lesson_no: 10,
    when_to_say: "Used to describe something complex.",
    example:
      "El problema es muy complicado. - The problem is very complicated.",
  },
  {
    id: "word041",
    word: "perseverancia",
    pronunciation: "pehr-seh-veh-rahn-syah",
    meaning: "perseverance",
    part_of_speech: "noun",
    difficulty: "difficult",
    lesson_no: 10,
    when_to_say: "Used to describe persistence in doing something.",
    example:
      "La perseverancia es clave para el éxito. - Perseverance is key to success.",
  },
  {
    id: "word042",
    word: "creatividad",
    pronunciation: "kreh-ah-tee-vee-dahd",
    meaning: "creativity",
    part_of_speech: "noun",
    difficulty: "difficult",
    lesson_no: 10,
    when_to_say: "Used to refer to the ability to create or innovate.",
    example:
      "La creatividad es importante en el diseño. - Creativity is important in design.",
  },
  {
    id: "word043",
    word: "estrategia",
    pronunciation: "ehs-trah-teh-hyah",
    meaning: "strategy",
    part_of_speech: "noun",
    difficulty: "difficult",
    lesson_no: 10,
    when_to_say: "Used to describe a plan of action.",
    example:
      "Necesitamos una buena estrategia para ganar. - We need a good strategy to win.",
  },
  {
    id: "word044",
    word: "satisfacción",
    pronunciation: "sah-tees-fahk-syohn",
    meaning: "satisfaction",
    part_of_speech: "noun",
    difficulty: "difficult",
    lesson_no: 10,
    when_to_say: "Used to express a sense of fulfillment.",
    example:
      "Siento una gran satisfacción por mi trabajo. - I feel great satisfaction with my work.",
  },
  {
    id: "word045",
    word: "resiliencia",
    pronunciation: "reh-see-lyehn-syah",
    meaning: "resilience",
    part_of_speech: "noun",
    difficulty: "difficult",
    lesson_no: 10,
    when_to_say: "Used to describe the ability to recover from adversity.",
    example:
      "La resiliencia es fundamental en momentos difíciles. - Resilience is fundamental in tough times.",
  },
  {
    id: "word046",
    word: "determinación",
    pronunciation: "deh-tehr-mee-nah-syohn",
    meaning: "determination",
    part_of_speech: "noun",
    difficulty: "difficult",
    lesson_no: 10,
    when_to_say: "Used to describe firmness of purpose.",
    example:
      "Su determinación es inspiradora. - Her determination is inspiring.",
  },
  {
    id: "word047",
    word: "colaboración",
    pronunciation: "koh-lah-boh-rah-syohn",
    meaning: "collaboration",
    part_of_speech: "noun",
    difficulty: "difficult",
    lesson_no: 10,
    when_to_say: "Used to describe working together.",
    example:
      "La colaboración mejora los resultados. - Collaboration improves results.",
  },
  {
    id: "word048",
    word: "sostenible",
    pronunciation: "sohs-teh-nee-bleh",
    meaning: "sustainable",
    part_of_speech: "adjective",
    difficulty: "difficult",
    lesson_no: 10,
    when_to_say: "Used to describe something that can be maintained long-term.",
    example:
      "Necesitamos soluciones sostenibles. - We need sustainable solutions.",
  },
  {
    id: "word049",
    word: "empatía",
    pronunciation: "ehm-pah-tee-ah",
    meaning: "empathy",
    part_of_speech: "noun",
    difficulty: "difficult",
    lesson_no: 10,
    when_to_say: "Used to describe the ability to understand others' feelings.",
    example:
      "La empatía es esencial en las relaciones humanas. - Empathy is essential in human relationships.",
  },
  {
    id: "word050",
    word: "innovación",
    pronunciation: "een-noh-vah-syohn",
    meaning: "innovation",
    part_of_speech: "noun",
    difficulty: "difficult",
    lesson_no: 10,
    when_to_say: "Used to describe the act of creating new ideas or methods.",
    example: "La innovación impulsa el progreso. - Innovation drives progress.",
  },
];
export default spanishWords;
